---
title: "Prompt Demo"
author: "Carlo"
date: "2023-06-29"
output: 
  html_document: 
    toc: true
    theme: flatly
    highlight: tango
---


```{r packages, message=FALSE, warning=FALSE, eval=FALSE}

# Load packages
library(tidyverse)
library(scales)
library(ggthemes)
library(ggrepel)
library(ggridges)
library(patchwork)
library(gganimate)
library(ggpubr)
library(ggmap)
library(ggExtra)
library(cowplot)
library(ggforce)
library(ggsignif)
library(stringr)
library(here)
```


```{r read data, message=FALSE, warning=FALSE, eval=FALSE}
# Read the csv files into R dataframes

# Climate Change
land_temp_country <- read_csv("data/GlobalLandTemperaturesByCountry.csv")
land_temp_city <- read_csv("data/GlobalLandTemperaturesByMajorCity.csv")
global_temp <- read_csv("data/GlobalTemperatures.csv")

# New York City Squirrel Census
nyc_squirrels <- read_csv("data/nyc_squirrels.csv")

# Pokemon
pokemon <- read_csv("data/pokemon.csv")
```

```{r plot}
# Convert tibble to data frame
nyc_squirrels <- as.data.frame(nyc_squirrels)

# Convert logical columns to numeric (0/1)
logical_cols <- c("running", "chasing", "climbing", "eating", "foraging")
nyc_squirrels[logical_cols] <- nyc_squirrels[logical_cols] %>% mutate_all(as.numeric)

# Calculate the percentage of true values for each column
percentage_true <- nyc_squirrels[logical_cols] %>% 
  summarise(across(everything(), ~mean(.x, na.rm = TRUE) * 100))

# Create a bar plot dataframe
plot_data <- percentage_true %>% 
  pivot_longer(cols = everything(), names_to = "column", values_to = "percentage_true") %>%
  mutate(column = str_to_title(column))  # Capitalize the first letter of each column title

# Plot
ggplot(plot_data, aes(x = reorder(column, -percentage_true), y = percentage_true, fill = column)) +
  geom_bar(stat = "identity", fill = "steelblue", width = 0.8, position = "identity") +
  coord_flip() +
  labs(y = "Percentage of Observations", x = "Behavior", title = "Percentage of Squirrels Exhibiting Various Behaviors") +
  geom_vline(xintercept = c(10, 20, 30, 40), linetype="solid", color = "black", linewidth=0.2) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.y = element_text(
      angle = 0,
      hjust = 1,
      vjust = 0.5,
      face = "bold",
      size = 12,
      margin = margin(r = -5)
    ),
    axis.text.x = element_text(face = "bold"),
    axis.ticks = element_line(color = "black", size = 0.5),
    panel.background = element_blank(),
    panel.grid.major.x = element_line(color = "gray", linetype = "solid", size = 0.5),
    legend.position = "none",
    plot.title = element_text(face = "bold", hjust = 0.5, size = 15),
    axis.title.x = element_text(face = "bold"),
    axis.title.y = element_blank()
  )
```

